# Generated by Django 5.0.2 on 2024-03-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=30)),
                ('job_location', models.CharField(max_length=30)),
                ('job_salary', models.FloatField()),
                ('job_type', models.CharField(max_length=30)),
                ('job_desc', models.TextField()),
            ],
        ),
    ]
