# Generated by Django 5.0.2 on 2024-04-01 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_pic',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
