# Generated by Django 5.0.2 on 2024-04-10 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_number', models.IntegerField()),
                ('donate_holder', models.CharField(max_length=30)),
                ('donate_expiry', models.DateField()),
                ('donate_cvc', models.CharField(max_length=30)),
            ],
        ),
    ]
