# Generated by Django 5.0.2 on 2024-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signin_name', models.CharField(max_length=30)),
                ('signin_email', models.CharField(max_length=30)),
                ('signin_password', models.CharField(max_length=30)),
            ],
        ),
    ]
