# Generated by Django 5.0.2 on 2024-04-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_title', models.CharField(max_length=30)),
                ('team_name', models.CharField(max_length=30)),
                ('team_salary', models.FloatField()),
                ('team_pic', models.CharField(max_length=30)),
            ],
        ),
    ]
