# Generated by Django 5.0.2 on 2024-04-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_name', models.CharField(max_length=30)),
                ('signup_email', models.CharField(max_length=30)),
                ('signup_password', models.CharField(max_length=30)),
            ],
        ),
    ]
